name: Test-2

on:
  push:
    branches: [ main ]

jobs:
  test1:
    uses: ./.github/workflows/test1.yml
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.envPAT }}

