name: Test-1

on:
  push:
    branches: [ main ]

jobs:
  test1:
    runs-on: ubuntu-latest
    name: test1
    uses: ./.github/workflows/workflow-2.yml
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: ${{ secrets.envPAT }}

    steps:
      - name: Show an echo output
        run: echo "Testing ... 1"
